# Dockerfile
FROM node:18-alpine

WORKDIR /app

# ARGs für Build-Zeit-Variablen
ARG MONGODB_URL="mongodb://127.0.0.1:27017/solun"
ARG NEXT_PUBLIC_MAIN_DOMAIN='dev.solun.pm'
ARG NEXT_PUBLIC_AUTH_DOMAIN='dev-auth.solun.pm'
ARG NEXT_PUBLIC_WEBMAIL_DOMAIN='dev-webmail.solun.pm'

# ENVs für Laufzeit-Variablen
ENV MONGODB_URL=$MONGODB_URL
ENV NEXT_PUBLIC_MAIN_DOMAIN=$NEXT_PUBLIC_MAIN_DOMAIN
ENV NEXT_PUBLIC_AUTH_DOMAIN=$NEXT_PUBLIC_AUTH_DOMAIN
ENV NEXT_PUBLIC_WEBMAIL_DOMAIN=$NEXT_PUBLIC_WEBMAIL_DOMAIN

COPY . .

RUN npm install
RUN npm run build

CMD ["npm", "run", "start"]
